image: php:7.2

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git -yqq
  - docker-php-ext-install pdo_mysql
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

services:
  - mysql

variables:
  MYSQL_DATABASE: root
  MYSQL_ROOT_PASSWORD: root

test:php7.2:mysql:
  image: php:7.2
  script:
    - vendor/bin/phpunit --configuration ./src/test/phpunit_mysql.xml --coverage-text
