version: '3'

services:
    web:
        container_name: html_server
        image: lavoweb/php-5.6
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
        links:
            - db:db
    db:
        container_name: database
        image: mysql:5.5
        volumes:
            - ~/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db