version: '3'

services:
  web:
    container_name: PHP_APACHE
    image: lavoweb/php-7.2
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    links:
      - mysql_db:db
  mysql_db:
    container_name: MYSQL
    image: mysql:5.5
    volumes:
      - ~/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    container_name: PMA
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql_db:db